# Generated by Django 6.0.6 on 2026-06-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_memebers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='memebers',
            new_name='members',
        ),
    ]
