# Generated by Django 5.2.15 on 2026-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_delete_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
